### ISSUE TITLE
Breaks `asdf global direnv system`

### ISSUE THREAD

**Issue by geoelectric** [zimfw/asdf#3]
This isn't your fault so much as the developers of asdf and asdf-direnv colliding. 

asdf seems to have made the curious design choice that if you set the tool to system, you cannot `asdf exec` it--the shim doesn't know how to bust through to whatever is on the path in that case.

That, in turn, breaks the asdf-direnv suggestion that you do not path the shims directory and that you `asdf exec` any tool for which you'd otherwise path. This only works when global is set to an installed version rather than system passthrough. Otherwise, you specifically have to *not* `asdf exec` it if it's set to system, and remember to use the one on the default path instead.

And *that*, in turn, breaks your added idea to alias direnv to `asdf exec direnv` because that pretty much unconditionally blocks all system direnv usage.

I'd recommend ignoring asdf-direnv's suggestion not to path the shims directory. It's a nice idea, but It causes all kinds of problems with programs finding each other if you only use exec/aliases (for example, vim can't find nodejs for Copilot, or cargo for code-minimap, etc.)

Despite asdf-direnv's claims, most of these programs don't mind finding a passthrough shim instead--virtualenv, pyenv, nvm, etc made everyone compatible with that pattern. But they *do* mind the app not being on the path at all. I'd already had to start adding shims back to my path after the plugin ran, so I think skipping that whole "optimization" is a great idea. 

You can always `asdf direnv local` when you do want the paths pinned for speed without having to operate that way all the time by nuking the shim path.

But if you do keep that quesitonably-advised behavior--especially your added sauce of aliasing direnv to *only* go through asdf--you'll somehow need to account for the idea that "system" isn't routed by `asdf exec` and have the direnv alias/function special case for that.

**Comment by ericbn** [comment]
We could check if the system version of direnv is currently being used or not, and only activate the asdf-direnv suggested optimizations if it's not.

Or you could report this directly the [asdf-direnv plugin](https://github.com/asdf-community/asdf-direnv). Maybe it's something they can fix on their side, so the suggested optimization also works with the system instalation.

**Comment by ericbn** [comment]
Looks like you don't need to initialize asdf during the shell startup if you're using the system direnv. This is what I've done:
1. Install direnv with system package manager
1. Uninstall any direnv installed with asdf
1. Keep the asdf direnv plugin installed
1. Make sure you have ~/.config/direnv/lib/use_asdf.sh
1. Make sure your .envrc files have `use asdf`
1. Remove `zmodule asdf` from .zimrc or any asdf initialization from .zshrc
1. Make sure you're initializing direnv during shell start-up, with `source <(direnv hook zsh)` in your .zshrc or any other preferred way 

Works like a charm. Basically you're using direnv to activate asdf this way. Since it's a system wide direnv, that does not depend on asdf to work, it's a much simpler setup.
